/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBackground: typeof import('./components/AppBackground.vue')['default']
    AuthDialog: typeof import('./components/AuthDialog.vue')['default']
    Chat: typeof import('./components/chat/Chat.vue')['default']
    ChatPlaceholder: typeof import('./components/ChatPlaceholder.vue')['default']
    CreateSelectDialog: typeof import('./components/dialogs/CreateSelectDialog.vue')['default']
    CustomNav: typeof import('./components/CustomNav.vue')['default']
    CustomTabBar: typeof import('./components/CustomTabBar.vue')['default']
    GroupChat: typeof import('./components/chat/GroupChat.vue')['default']
    GroupRoleMsg: typeof import('./components/chat/GroupRoleMsg.vue')['default']
    InputBox: typeof import('./components/chat/InputBox.vue')['default']
    InputSheet: typeof import('./components/dialogs/InputSheet.vue')['default']
    MemoryDisplay: typeof import('./components/common/MemoryDisplay.vue')['default']
    MemorySheet: typeof import('./components/common/MemorySheet.vue')['default']
    ModelErrDialog: typeof import('./components/dialogs/ModelErrDialog.vue')['default']
    ModelSheet: typeof import('./components/dialogs/ModelSheet.vue')['default']
    PagePlaceholder: typeof import('./components/PagePlaceholder.vue')['default']
    PointsRechargeDialog: typeof import('./components/dialogs/PointsRechargeDialog.vue')['default']
    RoleHotBadge: typeof import('./components/common/RoleHotBadge.vue')['default']
    RoleMsg: typeof import('./components/chat/RoleMsg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectSheet: typeof import('./components/dialogs/SelectSheet.vue')['default']
    StoryDialog: typeof import('./components/dialogs/StoryDialog.vue')['default']
    TipDialog: typeof import('./components/dialogs/TipDialog.vue')['default']
    UserMsg: typeof import('./components/chat/UserMsg.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSlider: typeof import('vant/es')['Slider']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanSwitch: typeof import('vant/es')['Switch']
    VanToast: typeof import('vant/es')['Toast']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
